version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terravista_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
      - node
    networks:
      - terravista

  node:
    image: node:20-alpine
    container_name: terravista_node
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"

  nginx:
    image: nginx:alpine
    container_name: terravista_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - terravista

  postgres:
    image: postgres
    container_name: terravista_postgres
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      POSTGRES_DB: terravista
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: lucas
    volumes:
      - ./.docker/postgres/dbdata:/var/lib/postgresql/data
    ports:
      - "8081:3306"
    networks:
      - terravista

networks:
  terravista:
    driver: bridge
